# Builds using pip and tests using pytest

name: OxPy Linux

on: push

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        py: ['3.6', '3.7', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.py}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install numpy
    - name: Build oxDNA, install and reinstall oxpy
      run: |
        python -m pip install .
        pip uninstall oxpy -y
        python -m pip install .
    - name: Check import from Command Line
      run: |
        mkdir test-folder && pushd test-folder
        python -c 'import oxpy'
